name: Lint and build

on:
  push:
    branches: [main]
    paths:
      - "src/**/*"
      - "test/**/*"
  pull_request:
    branches: [main]
    paths:
      - "src/**/*"
      - "test/**/*"

jobs:
  ling-and-build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.13.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: Run npm ci
        working-directory: ./
        run: npm ci
      - name: Run lint
        working-directory: ./
        run: npm run lint
      - name: Run prisma generate
        working-directory: ./
        run: npm run prisma:generate
      - name: Run build
        working-directory: ./
        run: npm run build
